apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 3  # Number of replicas (adjust as needed)
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: kamalbasha/nodejsapp:latest  #Docker image
        ports:
        - containerPort: 3000  # Port your Node.js app 

